// ── Infrastructure asset model ──────────────────────────────────────────────
// BOOTSTRAP-ONLY data. The live source of truth is now the snapshot.json
// shipped with each build, NOT this file. This array is consumed by
// migrateInfrastructure() exactly ONCE per fresh browser to seed empty
// localStorage. Once any sub-map has assets in localStorage, this file is
// never read again (the migration short-circuits — see the safety net in
// data/migrateInfrastructure.ts).
//
// DO NOT edit this file to update the live map. Edit the snapshot via the
// running app (which writes localStorage), then export via the build pipeline.
// Editing this file ONLY affects the cold-start seed for visitors with no
// existing data — a code change here is invisible to any returning visitor.
//
// Each asset belongs to exactly one sub-map. The sub-map is where the asset is
// placed and edited; the overview map *projects* these assets into each
// sub-map's calibrated region box (see data/submapRegions.ts) so an asset is
// defined once and shown in both views.
//
// Naming / IDs are standardised and global per type — Transformer 1..N and
// MPAN 1..N run as one unbroken sequence across the whole campus, regardless
// of sub-map. IDs are structured and stable (`transformer-07`) so cables,
// panels, energy data and future backend records can reference an asset by a
// permanent key rather than by its (editable) display name.
//
// Batteries are deliberately NOT in this model yet — they remain a temporary
// overview-only layer until they are placed properly on the sub-maps.
//
// Positions (x, y) are percentages of the SUB-MAP canvas and stay editable
// in-app. Assets migrated from the old overview layer are parked in a grid on
// the left edge of their new sub-map, ready to be dragged into place.

import type { AssetType } from './assets';

// Parent sub-map ids — must match the ids in data/submaps.ts.
export type SubMapId = 'etihad-stadium-map' | 'cfa-map' | 'co-op-live-map';

export interface InfrastructureAsset {
  /** Structured, permanent, unique id — e.g. 'transformer-07'. */
  id: string;
  /** Display name — e.g. 'Transformer 7'. Editable; never used as a key. */
  name: string;
  /** Asset type — drives the marker icon / colour (see data/assetTypes.ts). */
  type: AssetType;
  /** The sub-map this asset belongs to — its single home. */
  subMapId: SubMapId;
  /** Parent site label. Currently mirrors the sub-map's site. */
  site: string;
  /** Position as a percentage of the sub-map canvas. Editable in-app. */
  x: number;
  y: number;
  /** Real MPAN number, where known (MPAN assets only). */
  mpan?: string;
  /** Free-text notes. */
  notes?: string;
  /** Extensible metadata bag — make, rating, etc. Backend-ready. */
  metadata?: Record<string, string>;
  /** Reserved — link to an energy dataset by id (not by name). */
  energyKey?: string;
  /** Reserved — link to a future half-hourly dataset by id. */
  hhDataKey?: string;
}

// Sub-map id → parent site label.
export const SUBMAP_SITE: Record<SubMapId, string> = {
  'etihad-stadium-map': 'Etihad Stadium',
  'cfa-map': 'City Football Academy',
  'co-op-live-map': 'Co-op Live',
};

export const infrastructure: InfrastructureAsset[] = [
  // ── Etihad Stadium ────────────────────────────────────────────────────────
  // MPANs 5-7 on the Etihad sub-map.
  { id: 'mpan-05', name: 'MPAN 5', type: 'mpan', subMapId: 'etihad-stadium-map', site: 'Etihad Stadium', x: 38.31, y: 56.08 },
  { id: 'mpan-06', name: 'MPAN 6', type: 'mpan', subMapId: 'etihad-stadium-map', site: 'Etihad Stadium', x: 46.18, y: 22.27 },
  { id: 'mpan-07', name: 'MPAN 7', type: 'mpan', subMapId: 'etihad-stadium-map', site: 'Etihad Stadium', x: 50, y: 21.53 },
  // Transformer 1 already on the Etihad sub-map.
  { id: 'transformer-01', name: 'Transformer 1', type: 'transformer', subMapId: 'etihad-stadium-map', site: 'Etihad Stadium', x: 39.21, y: 53.75 },
  // Substation 1 (Rowsley Street) removed from the infrastructure template —
  // marker dropped from the map per the user's request.
  // Diesel Generators 3-4 (Cummins) already on the Etihad sub-map.
  { id: 'diesel-generator-03', name: 'Diesel Generator 3', type: 'diesel-generator', subMapId: 'etihad-stadium-map', site: 'Etihad Stadium', x: 39.98, y: 56.38, metadata: { make: 'Cummins', rating: '750 kVA' } },
  { id: 'diesel-generator-04', name: 'Diesel Generator 4', type: 'diesel-generator', subMapId: 'etihad-stadium-map', site: 'Etihad Stadium', x: 63.01, y: 48.56, metadata: { make: 'Cummins', engine: 'Cummins VTA-28-GS', alternator: 'Stamford HC1534F1', rating: '706 kVA' } },

  // ── City Football Academy ─────────────────────────────────────────────────
  // MPANs 11-13 on the CFA sub-map.
  { id: 'mpan-11', name: 'MPAN 11', type: 'mpan', subMapId: 'cfa-map', site: 'City Football Academy', x: 54.9, y: 13.49 },
  { id: 'mpan-12', name: 'MPAN 12', type: 'mpan', subMapId: 'cfa-map', site: 'City Football Academy', x: 55.21, y: 84.94 },
  { id: 'mpan-13', name: 'MPAN 13', type: 'mpan', subMapId: 'cfa-map', site: 'City Football Academy', x: 38.57, y: 84.25 },
  // Transformers 7-14 on the CFA sub-map.
  { id: 'transformer-07', name: 'Transformer 7', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 29.84, y: 35.05 },
  { id: 'transformer-08', name: 'Transformer 8', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 53.67, y: 39.71 },
  { id: 'transformer-09', name: 'Transformer 9', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 48.89, y: 60.73 },
  { id: 'transformer-10', name: 'Transformer 10', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 56.92, y: 58.01 },
  { id: 'transformer-11', name: 'Transformer 11', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 63.46, y: 73.43 },
  { id: 'transformer-12', name: 'Transformer 12', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 37.41, y: 32.06 },
  { id: 'transformer-13', name: 'Transformer 13', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 51.37, y: 15.02 },
  { id: 'transformer-14', name: 'Transformer 14', type: 'transformer', subMapId: 'cfa-map', site: 'City Football Academy', x: 56.23, y: 84.06 },
  // Substations 4-5 on the CFA sub-map.
  { id: 'substation-04', name: 'Substation 4', type: 'substation', subMapId: 'cfa-map', site: 'City Football Academy', x: 40.23, y: 80.91 },
  { id: 'substation-05', name: 'Substation 5', type: 'substation', subMapId: 'cfa-map', site: 'City Football Academy', x: 53.88, y: 85.23 },
  // Wind turbines already on the CFA sub-map (placement options A/B/C).
  { id: 'wind-turbine-01', name: 'Wind Turbine 1', type: 'wind-turbine', subMapId: 'cfa-map', site: 'City Football Academy', x: 60.15, y: 60.9, metadata: { option: 'A' } },
  { id: 'wind-turbine-02', name: 'Wind Turbine 2', type: 'wind-turbine', subMapId: 'cfa-map', site: 'City Football Academy', x: 43.68, y: 40.72, metadata: { option: 'B' } },
  { id: 'wind-turbine-03', name: 'Wind Turbine 3', type: 'wind-turbine', subMapId: 'cfa-map', site: 'City Football Academy', x: 62.21, y: 23.9, metadata: { option: 'C' } },
  // CHP machines already on the CFA sub-map.
  { id: 'chp-01', name: 'CHP Machine 1', type: 'chp', subMapId: 'cfa-map', site: 'City Football Academy', x: 55.76, y: 42.19, notes: 'Each CHP unit: 310 kWe / 2,500 kWth. The two units combined provide ~620 kWe electrical and ~5 MW thermal.', metadata: { rating: '310 kWe / 2,500 kWth' } },
  { id: 'chp-02', name: 'CHP Machine 2', type: 'chp', subMapId: 'cfa-map', site: 'City Football Academy', x: 54.74, y: 41.02, notes: 'Each CHP unit: 310 kWe / 2,500 kWth. The two units combined provide ~620 kWe electrical and ~5 MW thermal.', metadata: { rating: '310 kWe / 2,500 kWth' } },
  // Diesel Generator 1 (FG Wilson) migrated from the old overview layer.
  // Diesel Generator 2 (the second CFA FG Wilson unit) is still to be placed.
  { id: 'diesel-generator-01', name: 'Diesel Generator 1', type: 'diesel-generator', subMapId: 'cfa-map', site: 'City Football Academy', x: 14, y: 42, metadata: { make: 'FG Wilson', engine: 'Perkins 1106C-E66TAG4', alternator: 'Leroy Somer LL5014D', rating: '200 kVA' } },

  // ── Co-op Live ────────────────────────────────────────────────────────────
  { id: 'mpan-14', name: 'MPAN 14', type: 'mpan', subMapId: 'co-op-live-map', site: 'Co-op Live', x: 72.38, y: 51.35 },
];

/** Every infrastructure asset belonging to a given sub-map. */
export function infrastructureForSubMap(subMapId: string): InfrastructureAsset[] {
  return infrastructure.filter((a) => a.subMapId === subMapId);
}

/** Look up a single infrastructure asset by its permanent id. */
export function infrastructureById(id: string): InfrastructureAsset | undefined {
  return infrastructure.find((a) => a.id === id);
}
